spring.application.name=server

server.address=0.0.0.0
server.port=3434

spring.data.jpa.repositories.enabled=true
spring.datasource.url=jdbc:mysql://localhost:6603/gory

spring.datasource.username=seo
spring.datasource.password=Whdcks332980#

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.hibernate.ddl-auto= update


spring.servlet.multipart.max-file-size: 50MB
spring.servlet.multipart.max-request-size: 50MB

gory.app.jwtSecret=DrSecretKey
gory.app.jwtExpirationMs= 86400000

# upload.image.location=/var/www/html/gory/images/
# get.image.location=http://43.200.33.103/gory/images/

upload.image.location=C://MAMP/htdocs/gory/images/
get.image.location=http://localhost/gory/images/

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# JavaMailSender mail 설정
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sj012944@gmail.com
spring.mail.password=cfalribjyaqtyhoa
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.timeout = 5000
spring.mail.properties.mail.smtp.starttls.enable=true